additional include to override vars
nexient-llc/tf-module-skeleton pull request #6
Opened 2023-07-31 20:23 UTC by stephenpc

2023-08-01 13:27 UTC, ssdnex approved these changes

2023-08-02 17:03 UTC, dresdencraft requested changes
see in line comments

2023-08-02 17:03 UTC, dresdencraft commented on Makefile
>  REPO_REV ?= main
Add comment of the supported values

2023-08-02 17:03 UTC, dresdencraft commented on README.md
> +When run, `make` will look for a file called `.cafenv` in `$HOME` and the local directory. This file if present will be included, and it can be used to override variables without altering the [Makefi
update this to working dir

2023-08-02 17:42 UTC, ssdnex commented on Makefile
> +-include $(HOME)/$(CAF_ENV_FILE)
`repo` doesn't support tags at this point, only branches
https://source.android.com/docs/setup/create/repo#init

2023-08-02 18:33 UTC, stephenpc commented on Makefile
> +-include $(HOME)/$(CAF_ENV_FILE)
@dresdencraft The line below (L20) assumes the root of the repository

2023-08-02 18:34 UTC, stephenpc commented on Makefile
> +-include $(HOME)/$(CAF_ENV_FILE)
@dresdencraft Do you want to have ONLY the root of the repo be the location of this file?

2023-08-15 15:43 UTC, stephenpc commented
@dresdencraft I've addressed the inline comments. Please re-review.

2023-08-17 17:33 UTC, nexient-phil approved these changes

2023-08-17 19:39 UTC, merged